export const ophthalmologyServices = [
    { service: 'Specijalistički oftalmološki pregled', price: '60 €' },
    { service: 'Specijalistički pregled za upale/ozljede oka/odstranjivanje stranog tijela', price: '50 €' },
    { service: 'Predoperativni obrada za operaciju mrene', price: '150 €' },
    { service: 'Korekcija za naočale', price: '30 €' },
    { service: 'Mjerenje očnog tlaka', price: '20 €' },
    { service: 'Pregled s Goldmanovom prizmom', price: '70 €' },
    { service: 'OCT', price: '60 €' },
    { service: 'Kompjuterizirano vidno polje', price: '40 €' },
    { service: 'Pahimetrija', price: '20 €' },
    { service: 'Kompletna glaukomska obrada', price: '150 €' },
    { service: 'Obrada za suho oko', price: '80 €' },
    { service: 'UZV B- scan / A- scan', price: '30 €' },
    { service: 'Fundus kamera', price: '30 €' },
    { service: 'Prvi pregled za kontaktne leće', price: '60 €' },
    { service: 'Kontrolni pregled za kontakne leće', price: '30 €' },
    { service: 'Prvi pregled za polutvrde kontaktne leće', price: '70 €' },
    { service: 'Kontrolni pregled za polutvrde kontaktne leće', price: '35 €' },
    { service: 'Prvi pregled za multifokalne kontaktne leće', price: '80 €' },
    { service: 'Kontrolni pregled za multifokalne kontaktne leće', price: '40 €' },
    { service: 'Zamjena terapijske kontaktne leće', price: '10 €' },
    { service: 'Kortikosterodine injekcije', price: '10 €' },
    { service: 'Epilacija, proštrcavanje suznih kanala', price: '15 €' },
    { service: 'Operacija sive mrene (katarakte)', price: '',
        notes: [
            'Monofokalna leća – 900 €',
            'Monofokalna premium leća (Eyhance) – 1300 €',
            'Multifokalna leća (Synergy) – 1700 €',
    ],
    },
    { service: 'Mali kirurški zahvati', price: '',
        notes: [
          'Ksantelazme – 200 €',
          'Halcion (ječmenac), veruke, fibrom – 100 €',
          'Aterom – 130 €',
        ],
    },
    { service: 'Operacija pterigija', price: '300 €' },
    { service: 'Operacija pingvekule', price: '200 €' },
  ];
  
  export const aestheticServices = [
    { service: 'BOTOX 50 IU', price: '250 €' },
    { service: 'BOTOX 100 IU', price: '350 €' },
    { service: 'BOTOX “lip flip”', price: '100 €' },
    { service: 'DERMALNI FILER 0,5 ml', price: '200€' },
    { service: 'Dermalni filer 1 ml', price: '300 €' },
    { service: 'SkinPen', price: '130 €' },
    { service: 'Paket od 3 SkinPen', price: '' },
    { service: 'SkinPen uz PRP', price: '200 €' },
    { service: 'SkinPen uz egzosome', price: '300 €' },
    { service: 'Paket od 3 SkinPen s egosomima', price: '800 €' },
    { service: 'Mezoterapija', price: '200 €' },
    { service: 'PROFHILO (2 mL)', price: '300 €' },
    { service: 'PROFHILO Structura (2 mL)', price: '350 €' },
    { service: 'PROFHILO Body (3 mL)', price: '500 €' },
    { service: 'Revive (1ml / 2 ml)', price: '250 € / 450 €' },
    { service: 'PRP tretman', price: '120 €' },
    { service: 'Paket od 3 PRP tretmana', price: '300 €' },
    { service: 'Kemijski piling', price: '80 €' },
    { service: 'Parafin ruku', price: '25 €' },
    { service: 'PBserum (LOW, MED, HIGH)', price: '300 €' },
    { service: 'Sculptra (1 ampula)', price: '500 €' },
    { service: 'HYTHYA kolagen 3/1', price: '400 €' },
  ];
  